---
title: "Authors and subject by community"
output: github_document
---

#Prep data

```{r}

#setwd("code/work/")
options(stringsAsFactors = FALSE)
'%!in%' <- function(x,y)!('%in%'(x,y))

library(quanteda)
library(stringr)
library(ggplot2)
library(neo4r)
library(knitr)

con <- neo4j_api$new(
  url = "http://localhost:7474",
  user = "neo4j", 
  password = "1234"
)

#For 10 year chunks
#dfm_files <- list.files("../../data/work/netowrking_archives/dfm/", full.names = TRUE)
dfm_files <- list.files("../../ESTC_SNA_data_creation/data/work/netowrking_archives/com_dfm_titles/", full.names = TRUE)
#dfm_files <- dfm_files[-c(1:159)]
#dfm_files <- dfm_files[-c(267:length(dfm_files))] #update this if I can get the last few -1730

#stop words
latin_stopwords <- read.csv("../../ESTC_SNA_data_creation/data/raw/latin.stopwords.clean", stringsAsFactors = FALSE)
extra_stopwords <- c("shall", "may", "one", "us", "hath", "yet", "upon", "yet", "now", "said", "unto", "thy", "doe", "first", "must",
                     "much", "made", "many", "make", "also", "without", "can", "thou", "like", "can", "though", "therefore", "without",
                     "two", "things", "might", "way", "say", "day", "let", "well", "things", "take", "owne", "doth", "i.e", "tis", "page removed",
                     #THIS IS IMPORTANT!
                     "non-latin", "alphabet", "saith", "thus", "|", "¦", "⁻", "vol", "year", "printed", "published",
                     "na", "amp", "ye", "anno", "translated", "vpon", "vnto", "yeere", "haue", "three", "second", "thereof", "yeare", "written", "mr",
                     "wherein", "written", "esq", "author", "part", "dr", "volumes", "1800", "volume", "mrs", "m.d", "d.d", "b.d")
```

#Load DFMs, get authors, check DB for subjects

#17th Century

```{r}
eras <- unique(str_extract(dfm_files, "\\d\\d\\d\\d-\\d\\d\\d\\d"))
eras <- eras[grep("^16\\d\\d", eras)]
for(i_era in 1:length(eras)) {

  cat("\n", eras[i_era], "\n")
  
  temp_files <- dfm_files[grep(eras[i_era], dfm_files)]
  temp_dfm <- readRDS(temp_files)
  temp_dfm <- dfm_select(temp_dfm, pattern = c(stopwords("english"), stopwords("french"), stopwords("italian"), stopwords("spanish"), latin_stopwords$a, extra_stopwords), selection = "remove", valuetype = "fixed")
  temp_dfm <- dfm_select(temp_dfm, pattern = c("\\d\\d\\d\\d\\d", "\\d\\d\\d\\d", "\\d\\d\\d", "\\d\\d", "\\d"), selection = "remove", valuetype = "regex")
  
  com_num <- unique(temp_dfm@docvars$Community)

  #One era only has one community (1506-1515), so need to skip it
  if(length(com_num) == 1) { next }

  for(i_authors in 1:length(com_num)) {
    cat("\nAuthors for", eras[i_era], com_num[i_authors], "\n")
    temp_authors <- temp_dfm@docvars$author[which(temp_dfm@docvars$Community == com_num[i_authors])]
    temp_authors <- temp_authors[!is.na(temp_authors)]
    if(length(temp_authors) > 0) {
      print(kable(sort(table(temp_authors), decreasing = TRUE)))
    } else {
      cat("\nNo authors for community\n")
    }
    
    cat("\nSubjects for", eras[i_era], com_num[i_authors], "\n")
    temp_estc_id <- paste0(temp_dfm@docvars$estc_id[which(temp_dfm@docvars$Community == com_num[i_authors])], collapse = '", "')
    #getting subjects
    temp_subjects <- paste0('MATCH (d:Document)
    WHERE d.estc_id IN ["', temp_estc_id, '"] 
    RETURN d.simplified_dd_subject, d.subjects_600') %>%
      call_neo4j(con)
    
    if(length(temp_subjects[[1]]) == 0) {
      cat("\nNo simplified subjects recorded for this community\n")
    } else {
      temp_simp_subjects <- temp_subjects$d.simplified_dd_subject[[1]]
      temp_simp_subjects <- temp_simp_subjects[!is.na(temp_simp_subjects)]
    
      print(kable(sort(table(temp_simp_subjects), decreasing = TRUE)))
    }
    
    # if(length(temp_subjects[[1]]) == 0) {
    #   cat("\nNo ESTC subjects recorded for this community\n")
    # } else {
    #   temp_600 <- paste0(temp_subjects$d.subjects_600[[1]], collapse = ", ")
    #   
    #   temp_600 <- gsub("[[]", "", temp_600)
    #   temp_600 <- gsub("[]]", "", temp_600)
    #   temp_600 <- gsub("^'", "", temp_600)
    #   temp_600 <- gsub("'$", "", temp_600)
    #   
    #   temp_600 <- str_split(temp_600, "', '")[[1]]
    #   
    #   print(kable(sort(table(temp_600), decreasing = TRUE)))
    # }
  }
}
```

